### ISSUE TITLE
Outdated facts still in the package. 

### ISSUE THREAD

**Issue by PancakesWasTaken** [TabulateJarl8/randfacts#1]
I found an old fact that is now no longer true. Specifically, it's this one: "Every tweet Americans send is being archived by the Library of Congress." The Library stopped this in the year 2017 according to the date of an NPR post on the topic (https://www.npr.org/sections/thetwo-way/2017/12/26/573609499/library-of-congress-will-no-longer-archive-every-tweet).

**Comment by TabulateJarl8** [comment]
Thanks for pointing this out, if you find any more outdated facts please tell me

**Comment by TabulateJarl8** [comment]
I've fixed this in the 0.2.5 update
