### ISSUE TITLE
test.py failure to complete test 3/3

### ISSUE THREAD

**Issue by PancakesWasTaken** [TabulateJarl8/randfacts#3]
Bug info:
  The bug is a `FileNotFoundError` that originates in `test.py` and is affecting line 43 possibly line 46 (line numbers are from 
  the current 0.2.7 master) in the file due to a blank state in the variable `basedir`.

  1. Install the randfacts master on a test machine that is UNIX based 
  2. Install randfacts master into the system using `setup.py` 
  3. cd to tests and do `sudo python3 test.py`
  4. See Error

Intended result:
  The test was intended to be completed successfully with no issues and terminate with no problems.

Actual result:
  *SEE SCREENSHOT*

Screenshot before "suppression":
<img width="473" alt="Screen Shot 2021-01-28 at 8 22 04 AM" src="https://user-images.githubusercontent.com/75938196/106146508-beb2ee80-6144-11eb-936b-009cd822bd47.png">

Machine info:
 - OS: MacOS Catalina 10.15.7
 - Python version: 3.8.5
 - Package Version: 0.2.7 (but was detected on a 0.2.8 dev build)

Extras:
  The problem was "suppressed" by adding a `try-except` around the affected area.

**Comment by TabulateJarl8** [comment]
Should be fixed in 3c75ea79bfd1fbfa2ae3e916eb089fbabb148277
