### ISSUE TITLE
I can't get facts from the module

### ISSUE THREAD

**Issue by VG08** [TabulateJarl8/randfacts#7]
**Describe the bug**
I made a new file and ran
`import randfacts

x = randfacts.get_fact()

print(x)`

It is giving me  
  ` return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2678: character maps to 
<undefined>`

**Expected behavior**
It should give me a fact

**Please complete the following information:**
 - OS: Windows 10
 - Python version: python 3.9.5
 - Versionn: 0.7.3

**Comment by TabulateJarl8** [comment]
If you try again, does this happen? This may just be a Windows issue and I believe I've has issues with limited encoding on Windows before. I'll check it out later today or tomorrow because I'm busy today

**Comment by TabulateJarl8** [comment]
Another thing, can you post the full traceback?

**Comment by TabulateJarl8** [comment]
I've pushed a potential fix. Can you update using `pip3 install "randfacts>=0.7.4" --force-reinstall` in a terminal and then try again?

**Comment by VG08** [comment]
> I've pushed a potential fix. Can you update using `pip3 install "randfacts>=0.7.4" --force-reinstall` in a terminal and then try again?

yea it works now
thanks
